/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;

import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
    @Test public void testRandomQuote() throws FileNotFoundException {
        String expected = App.getQuote();
        String actual = App.getQuote();
        boolean isRandom = expected != actual;
        System.out.println("Actual: " + actual);
        System.out.println("Expected: " + expected);

        assertTrue(isRandom, "Should generate a random quote");
    }

}
