/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;

public class App {
    public static void main(String[] args) throws FileNotFoundException {

        System.out.println(App.getQuote());
    }

    public static String getQuote() throws FileNotFoundException {
        Gson gson = new Gson();
        String path = "/Users/dawoodabuzahra/401/quotes/app/src/main/resources/quotes.json";
        File file = new File(path);
        FileReader reader = new FileReader(file);
        Qoute[] qoutes = gson.fromJson(reader, Qoute[].class);
        int max = qoutes.length;
        int rand = (int)(Math.random()*max);
        return qoutes[rand].toString();
    }

}

